title: Adventures in Machine Learning
theme: minima
author: Chad Doebelin
email: chad.doebelin@gmail.com
description: I'm learning about how machines learn. Please follow along with me!

# social links
youtube_username: ChadDoebelin
twitter_username: ChadDoebelin 
github_username:  astrobleem 
linkedin_username: chaddoebelin

show_excerpts: true # set to false to remove excerpts on the homepage
